# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from anki_vector.messaging import behavior_pb2 as anki__vector_dot_messaging_dot_behavior__pb2
from anki_vector.messaging import cube_pb2 as anki__vector_dot_messaging_dot_cube__pb2
from anki_vector.messaging import messages_pb2 as anki__vector_dot_messaging_dot_messages__pb2
from anki_vector.messaging import settings_pb2 as anki__vector_dot_messaging_dot_settings__pb2
from anki_vector.messaging import shared_pb2 as anki__vector_dot_messaging_dot_shared__pb2


class ExternalInterfaceStub(object):
  """The grpc-defined connection between the SDK and Anki's Vector robot.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ProtocolVersion = channel.unary_unary(
        '/Anki.Vector.external_interface.ExternalInterface/ProtocolVersion',
        request_serializer=anki__vector_dot_messaging_dot_shared__pb2.ProtocolVersionRequest.SerializeToString,
        response_deserializer=anki__vector_dot_messaging_dot_shared__pb2.ProtocolVersionResponse.FromString,
        )
    self.DriveWheels = channel.unary_unary(
        '/Anki.Vector.external_interface.ExternalInterface/DriveWheels',
        request_serializer=anki__vector_dot_messaging_dot_messages__pb2.DriveWheelsRequest.SerializeToString,
        response_deserializer=anki__vector_dot_messaging_dot_messages__pb2.DriveWheelsResponse.FromString,
        )
    self.PlayAnimation = channel.unary_unary(
        '/Anki.Vector.external_interface.ExternalInterface/PlayAnimation',
        request_serializer=anki__vector_dot_messaging_dot_messages__pb2.PlayAnimationRequest.SerializeToString,
        response_deserializer=anki__vector_dot_messaging_dot_messages__pb2.PlayAnimationResponse.FromString,
        )
    self.ListAnimations = channel.unary_unary(
        '/Anki.Vector.external_interface.ExternalInterface/ListAnimations',
        request_serializer=anki__vector_dot_messaging_dot_messages__pb2.ListAnimationsRequest.SerializeToString,
        response_deserializer=anki__vector_dot_messaging_dot_messages__pb2.ListAnimationsResponse.FromString,
        )
    self.MoveHead = channel.unary_unary(
        '/Anki.Vector.external_interface.ExternalInterface/MoveHead',
        request_serializer=anki__vector_dot_messaging_dot_messages__pb2.MoveHeadRequest.SerializeToString,
        response_deserializer=anki__vector_dot_messaging_dot_messages__pb2.MoveHeadResponse.FromString,
        )
    self.MoveLift = channel.unary_unary(
        '/Anki.Vector.external_interface.ExternalInterface/MoveLift',
        request_serializer=anki__vector_dot_messaging_dot_messages__pb2.MoveLiftRequest.SerializeToString,
        response_deserializer=anki__vector_dot_messaging_dot_messages__pb2.MoveLiftResponse.FromString,
        )
    self.DisplayFaceImageRGB = channel.unary_unary(
        '/Anki.Vector.external_interface.ExternalInterface/DisplayFaceImageRGB',
        request_serializer=anki__vector_dot_messaging_dot_messages__pb2.DisplayFaceImageRGBRequest.SerializeToString,
        response_deserializer=anki__vector_dot_messaging_dot_messages__pb2.DisplayFaceImageRGBResponse.FromString,
        )
    self.EventStream = channel.unary_stream(
        '/Anki.Vector.external_interface.ExternalInterface/EventStream',
        request_serializer=anki__vector_dot_messaging_dot_shared__pb2.EventRequest.SerializeToString,
        response_deserializer=anki__vector_dot_messaging_dot_shared__pb2.EventResponse.FromString,
        )
    self.BehaviorControl = channel.stream_stream(
        '/Anki.Vector.external_interface.ExternalInterface/BehaviorControl',
        request_serializer=anki__vector_dot_messaging_dot_behavior__pb2.BehaviorControlRequest.SerializeToString,
        response_deserializer=anki__vector_dot_messaging_dot_behavior__pb2.BehaviorControlResponse.FromString,
        )
    self.AssumeBehaviorControl = channel.unary_stream(
        '/Anki.Vector.external_interface.ExternalInterface/AssumeBehaviorControl',
        request_serializer=anki__vector_dot_messaging_dot_behavior__pb2.BehaviorControlRequest.SerializeToString,
        response_deserializer=anki__vector_dot_messaging_dot_behavior__pb2.BehaviorControlResponse.FromString,
        )
    self.AppIntent = channel.unary_unary(
        '/Anki.Vector.external_interface.ExternalInterface/AppIntent',
        request_serializer=anki__vector_dot_messaging_dot_messages__pb2.AppIntentRequest.SerializeToString,
        response_deserializer=anki__vector_dot_messaging_dot_messages__pb2.AppIntentResponse.FromString,
        )
    self.CancelFaceEnrollment = channel.unary_unary(
        '/Anki.Vector.external_interface.ExternalInterface/CancelFaceEnrollment',
        request_serializer=anki__vector_dot_messaging_dot_messages__pb2.CancelFaceEnrollmentRequest.SerializeToString,
        response_deserializer=anki__vector_dot_messaging_dot_messages__pb2.CancelFaceEnrollmentResponse.FromString,
        )
    self.RequestEnrolledNames = channel.unary_unary(
        '/Anki.Vector.external_interface.ExternalInterface/RequestEnrolledNames',
        request_serializer=anki__vector_dot_messaging_dot_messages__pb2.RequestEnrolledNamesRequest.SerializeToString,
        response_deserializer=anki__vector_dot_messaging_dot_messages__pb2.RequestEnrolledNamesResponse.FromString,
        )
    self.UpdateEnrolledFaceByID = channel.unary_unary(
        '/Anki.Vector.external_interface.ExternalInterface/UpdateEnrolledFaceByID',
        request_serializer=anki__vector_dot_messaging_dot_messages__pb2.UpdateEnrolledFaceByIDRequest.SerializeToString,
        response_deserializer=anki__vector_dot_messaging_dot_messages__pb2.UpdateEnrolledFaceByIDResponse.FromString,
        )
    self.EraseEnrolledFaceByID = channel.unary_unary(
        '/Anki.Vector.external_interface.ExternalInterface/EraseEnrolledFaceByID',
        request_serializer=anki__vector_dot_messaging_dot_messages__pb2.EraseEnrolledFaceByIDRequest.SerializeToString,
        response_deserializer=anki__vector_dot_messaging_dot_messages__pb2.EraseEnrolledFaceByIDResponse.FromString,
        )
    self.EraseAllEnrolledFaces = channel.unary_unary(
        '/Anki.Vector.external_interface.ExternalInterface/EraseAllEnrolledFaces',
        request_serializer=anki__vector_dot_messaging_dot_messages__pb2.EraseAllEnrolledFacesRequest.SerializeToString,
        response_deserializer=anki__vector_dot_messaging_dot_messages__pb2.EraseAllEnrolledFacesResponse.FromString,
        )
    self.SetFaceToEnroll = channel.unary_unary(
        '/Anki.Vector.external_interface.ExternalInterface/SetFaceToEnroll',
        request_serializer=anki__vector_dot_messaging_dot_messages__pb2.SetFaceToEnrollRequest.SerializeToString,
        response_deserializer=anki__vector_dot_messaging_dot_messages__pb2.SetFaceToEnrollResponse.FromString,
        )
    self.EnableVisionMode = channel.unary_unary(
        '/Anki.Vector.external_interface.ExternalInterface/EnableVisionMode',
        request_serializer=anki__vector_dot_messaging_dot_messages__pb2.EnableVisionModeRequest.SerializeToString,
        response_deserializer=anki__vector_dot_messaging_dot_messages__pb2.EnableVisionModeResponse.FromString,
        )
    self.GoToPose = channel.unary_unary(
        '/Anki.Vector.external_interface.ExternalInterface/GoToPose',
        request_serializer=anki__vector_dot_messaging_dot_messages__pb2.GoToPoseRequest.SerializeToString,
        response_deserializer=anki__vector_dot_messaging_dot_messages__pb2.GoToPoseResponse.FromString,
        )
    self.DockWithCube = channel.unary_unary(
        '/Anki.Vector.external_interface.ExternalInterface/DockWithCube',
        request_serializer=anki__vector_dot_messaging_dot_messages__pb2.DockWithCubeRequest.SerializeToString,
        response_deserializer=anki__vector_dot_messaging_dot_messages__pb2.DockWithCubeResponse.FromString,
        )
    self.DriveOffCharger = channel.unary_unary(
        '/Anki.Vector.external_interface.ExternalInterface/DriveOffCharger',
        request_serializer=anki__vector_dot_messaging_dot_messages__pb2.DriveOffChargerRequest.SerializeToString,
        response_deserializer=anki__vector_dot_messaging_dot_messages__pb2.DriveOffChargerResponse.FromString,
        )
    self.DriveOnCharger = channel.unary_unary(
        '/Anki.Vector.external_interface.ExternalInterface/DriveOnCharger',
        request_serializer=anki__vector_dot_messaging_dot_messages__pb2.DriveOnChargerRequest.SerializeToString,
        response_deserializer=anki__vector_dot_messaging_dot_messages__pb2.DriveOnChargerResponse.FromString,
        )
    self.GetOnboardingState = channel.unary_unary(
        '/Anki.Vector.external_interface.ExternalInterface/GetOnboardingState',
        request_serializer=anki__vector_dot_messaging_dot_messages__pb2.OnboardingStateRequest.SerializeToString,
        response_deserializer=anki__vector_dot_messaging_dot_messages__pb2.OnboardingStateResponse.FromString,
        )
    self.SendOnboardingInput = channel.unary_unary(
        '/Anki.Vector.external_interface.ExternalInterface/SendOnboardingInput',
        request_serializer=anki__vector_dot_messaging_dot_messages__pb2.OnboardingInputRequest.SerializeToString,
        response_deserializer=anki__vector_dot_messaging_dot_messages__pb2.OnboardingInputResponse.FromString,
        )
    self.PhotosInfo = channel.unary_unary(
        '/Anki.Vector.external_interface.ExternalInterface/PhotosInfo',
        request_serializer=anki__vector_dot_messaging_dot_messages__pb2.PhotosInfoRequest.SerializeToString,
        response_deserializer=anki__vector_dot_messaging_dot_messages__pb2.PhotosInfoResponse.FromString,
        )
    self.Photo = channel.unary_unary(
        '/Anki.Vector.external_interface.ExternalInterface/Photo',
        request_serializer=anki__vector_dot_messaging_dot_messages__pb2.PhotoRequest.SerializeToString,
        response_deserializer=anki__vector_dot_messaging_dot_messages__pb2.PhotoResponse.FromString,
        )
    self.Thumbnail = channel.unary_unary(
        '/Anki.Vector.external_interface.ExternalInterface/Thumbnail',
        request_serializer=anki__vector_dot_messaging_dot_messages__pb2.ThumbnailRequest.SerializeToString,
        response_deserializer=anki__vector_dot_messaging_dot_messages__pb2.ThumbnailResponse.FromString,
        )
    self.DeletePhoto = channel.unary_unary(
        '/Anki.Vector.external_interface.ExternalInterface/DeletePhoto',
        request_serializer=anki__vector_dot_messaging_dot_messages__pb2.DeletePhotoRequest.SerializeToString,
        response_deserializer=anki__vector_dot_messaging_dot_messages__pb2.DeletePhotoResponse.FromString,
        )
    self.GetLatestAttentionTransfer = channel.unary_unary(
        '/Anki.Vector.external_interface.ExternalInterface/GetLatestAttentionTransfer',
        request_serializer=anki__vector_dot_messaging_dot_messages__pb2.LatestAttentionTransferRequest.SerializeToString,
        response_deserializer=anki__vector_dot_messaging_dot_messages__pb2.LatestAttentionTransferResponse.FromString,
        )
    self.PullJdocs = channel.unary_unary(
        '/Anki.Vector.external_interface.ExternalInterface/PullJdocs',
        request_serializer=anki__vector_dot_messaging_dot_settings__pb2.PullJdocsRequest.SerializeToString,
        response_deserializer=anki__vector_dot_messaging_dot_settings__pb2.PullJdocsResponse.FromString,
        )
    self.UpdateSettings = channel.unary_unary(
        '/Anki.Vector.external_interface.ExternalInterface/UpdateSettings',
        request_serializer=anki__vector_dot_messaging_dot_settings__pb2.UpdateSettingsRequest.SerializeToString,
        response_deserializer=anki__vector_dot_messaging_dot_settings__pb2.UpdateSettingsResponse.FromString,
        )
    self.UpdateAccountSettings = channel.unary_unary(
        '/Anki.Vector.external_interface.ExternalInterface/UpdateAccountSettings',
        request_serializer=anki__vector_dot_messaging_dot_settings__pb2.UpdateAccountSettingsRequest.SerializeToString,
        response_deserializer=anki__vector_dot_messaging_dot_settings__pb2.UpdateAccountSettingsResponse.FromString,
        )
    self.UpdateUserEntitlements = channel.unary_unary(
        '/Anki.Vector.external_interface.ExternalInterface/UpdateUserEntitlements',
        request_serializer=anki__vector_dot_messaging_dot_settings__pb2.UpdateUserEntitlementsRequest.SerializeToString,
        response_deserializer=anki__vector_dot_messaging_dot_settings__pb2.UpdateUserEntitlementsResponse.FromString,
        )
    self.DriveStraight = channel.unary_unary(
        '/Anki.Vector.external_interface.ExternalInterface/DriveStraight',
        request_serializer=anki__vector_dot_messaging_dot_messages__pb2.DriveStraightRequest.SerializeToString,
        response_deserializer=anki__vector_dot_messaging_dot_messages__pb2.DriveStraightResponse.FromString,
        )
    self.TurnInPlace = channel.unary_unary(
        '/Anki.Vector.external_interface.ExternalInterface/TurnInPlace',
        request_serializer=anki__vector_dot_messaging_dot_messages__pb2.TurnInPlaceRequest.SerializeToString,
        response_deserializer=anki__vector_dot_messaging_dot_messages__pb2.TurnInPlaceResponse.FromString,
        )
    self.SetHeadAngle = channel.unary_unary(
        '/Anki.Vector.external_interface.ExternalInterface/SetHeadAngle',
        request_serializer=anki__vector_dot_messaging_dot_messages__pb2.SetHeadAngleRequest.SerializeToString,
        response_deserializer=anki__vector_dot_messaging_dot_messages__pb2.SetHeadAngleResponse.FromString,
        )
    self.SetLiftHeight = channel.unary_unary(
        '/Anki.Vector.external_interface.ExternalInterface/SetLiftHeight',
        request_serializer=anki__vector_dot_messaging_dot_messages__pb2.SetLiftHeightRequest.SerializeToString,
        response_deserializer=anki__vector_dot_messaging_dot_messages__pb2.SetLiftHeightResponse.FromString,
        )
    self.UserAuthentication = channel.unary_unary(
        '/Anki.Vector.external_interface.ExternalInterface/UserAuthentication',
        request_serializer=anki__vector_dot_messaging_dot_shared__pb2.UserAuthenticationRequest.SerializeToString,
        response_deserializer=anki__vector_dot_messaging_dot_shared__pb2.UserAuthenticationResponse.FromString,
        )
    self.BatteryState = channel.unary_unary(
        '/Anki.Vector.external_interface.ExternalInterface/BatteryState',
        request_serializer=anki__vector_dot_messaging_dot_messages__pb2.BatteryStateRequest.SerializeToString,
        response_deserializer=anki__vector_dot_messaging_dot_messages__pb2.BatteryStateResponse.FromString,
        )
    self.VersionState = channel.unary_unary(
        '/Anki.Vector.external_interface.ExternalInterface/VersionState',
        request_serializer=anki__vector_dot_messaging_dot_messages__pb2.VersionStateRequest.SerializeToString,
        response_deserializer=anki__vector_dot_messaging_dot_messages__pb2.VersionStateResponse.FromString,
        )
    self.NetworkState = channel.unary_unary(
        '/Anki.Vector.external_interface.ExternalInterface/NetworkState',
        request_serializer=anki__vector_dot_messaging_dot_messages__pb2.NetworkStateRequest.SerializeToString,
        response_deserializer=anki__vector_dot_messaging_dot_messages__pb2.NetworkStateResponse.FromString,
        )
    self.SayText = channel.unary_unary(
        '/Anki.Vector.external_interface.ExternalInterface/SayText',
        request_serializer=anki__vector_dot_messaging_dot_messages__pb2.SayTextRequest.SerializeToString,
        response_deserializer=anki__vector_dot_messaging_dot_messages__pb2.SayTextResponse.FromString,
        )
    self.ConnectCube = channel.unary_unary(
        '/Anki.Vector.external_interface.ExternalInterface/ConnectCube',
        request_serializer=anki__vector_dot_messaging_dot_cube__pb2.ConnectCubeRequest.SerializeToString,
        response_deserializer=anki__vector_dot_messaging_dot_cube__pb2.ConnectCubeResponse.FromString,
        )
    self.DisconnectCube = channel.unary_unary(
        '/Anki.Vector.external_interface.ExternalInterface/DisconnectCube',
        request_serializer=anki__vector_dot_messaging_dot_cube__pb2.DisconnectCubeRequest.SerializeToString,
        response_deserializer=anki__vector_dot_messaging_dot_cube__pb2.DisconnectCubeResponse.FromString,
        )
    self.CubesAvailable = channel.unary_unary(
        '/Anki.Vector.external_interface.ExternalInterface/CubesAvailable',
        request_serializer=anki__vector_dot_messaging_dot_cube__pb2.CubesAvailableRequest.SerializeToString,
        response_deserializer=anki__vector_dot_messaging_dot_cube__pb2.CubesAvailableResponse.FromString,
        )
    self.FlashCubeLights = channel.unary_unary(
        '/Anki.Vector.external_interface.ExternalInterface/FlashCubeLights',
        request_serializer=anki__vector_dot_messaging_dot_cube__pb2.FlashCubeLightsRequest.SerializeToString,
        response_deserializer=anki__vector_dot_messaging_dot_cube__pb2.FlashCubeLightsResponse.FromString,
        )
    self.ForgetPreferredCube = channel.unary_unary(
        '/Anki.Vector.external_interface.ExternalInterface/ForgetPreferredCube',
        request_serializer=anki__vector_dot_messaging_dot_cube__pb2.ForgetPreferredCubeRequest.SerializeToString,
        response_deserializer=anki__vector_dot_messaging_dot_cube__pb2.ForgetPreferredCubeResponse.FromString,
        )
    self.SetPreferredCube = channel.unary_unary(
        '/Anki.Vector.external_interface.ExternalInterface/SetPreferredCube',
        request_serializer=anki__vector_dot_messaging_dot_cube__pb2.SetPreferredCubeRequest.SerializeToString,
        response_deserializer=anki__vector_dot_messaging_dot_cube__pb2.SetPreferredCubeResponse.FromString,
        )
    self.SetCubeLights = channel.unary_unary(
        '/Anki.Vector.external_interface.ExternalInterface/SetCubeLights',
        request_serializer=anki__vector_dot_messaging_dot_cube__pb2.SetCubeLightsRequest.SerializeToString,
        response_deserializer=anki__vector_dot_messaging_dot_cube__pb2.SetCubeLightsResponse.FromString,
        )
    self.AudioFeed = channel.unary_stream(
        '/Anki.Vector.external_interface.ExternalInterface/AudioFeed',
        request_serializer=anki__vector_dot_messaging_dot_messages__pb2.AudioFeedRequest.SerializeToString,
        response_deserializer=anki__vector_dot_messaging_dot_messages__pb2.AudioFeedResponse.FromString,
        )
    self.CameraFeed = channel.unary_stream(
        '/Anki.Vector.external_interface.ExternalInterface/CameraFeed',
        request_serializer=anki__vector_dot_messaging_dot_messages__pb2.CameraFeedRequest.SerializeToString,
        response_deserializer=anki__vector_dot_messaging_dot_messages__pb2.CameraFeedResponse.FromString,
        )
    self.CheckUpdateStatus = channel.unary_unary(
        '/Anki.Vector.external_interface.ExternalInterface/CheckUpdateStatus',
        request_serializer=anki__vector_dot_messaging_dot_messages__pb2.CheckUpdateStatusRequest.SerializeToString,
        response_deserializer=anki__vector_dot_messaging_dot_messages__pb2.CheckUpdateStatusResponse.FromString,
        )
    self.UpdateAndRestart = channel.unary_unary(
        '/Anki.Vector.external_interface.ExternalInterface/UpdateAndRestart',
        request_serializer=anki__vector_dot_messaging_dot_messages__pb2.UpdateAndRestartRequest.SerializeToString,
        response_deserializer=anki__vector_dot_messaging_dot_messages__pb2.UpdateAndRestartResponse.FromString,
        )
    self.UploadDebugLogs = channel.unary_unary(
        '/Anki.Vector.external_interface.ExternalInterface/UploadDebugLogs',
        request_serializer=anki__vector_dot_messaging_dot_messages__pb2.UploadDebugLogsRequest.SerializeToString,
        response_deserializer=anki__vector_dot_messaging_dot_messages__pb2.UploadDebugLogsResponse.FromString,
        )
    self.CheckCloudConnection = channel.unary_unary(
        '/Anki.Vector.external_interface.ExternalInterface/CheckCloudConnection',
        request_serializer=anki__vector_dot_messaging_dot_messages__pb2.CheckCloudRequest.SerializeToString,
        response_deserializer=anki__vector_dot_messaging_dot_messages__pb2.CheckCloudResponse.FromString,
        )


class ExternalInterfaceServicer(object):
  """The grpc-defined connection between the SDK and Anki's Vector robot.
  """

  def ProtocolVersion(self, request, context):
    """Checks the supported protocol version by passing in the client version and
    minimum host version and receiving a response to see whether the versions are supported.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DriveWheels(self, request, context):
    """Sets the speed and acceleration for Vector's wheel motors.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PlayAnimation(self, request, context):
    """Requests that Vector play an animation.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListAnimations(self, request, context):
    """Constructs and returns a list of animations.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def MoveHead(self, request, context):
    """Moves Vector's head.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def MoveLift(self, request, context):
    """Moves Vector's lift.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DisplayFaceImageRGB(self, request, context):
    """Sets screen (Vector's face) to a solid color.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def EventStream(self, request, context):
    """Streaming events endpoint
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def BehaviorControl(self, request_iterator, context):
    """Integrate with and acquire control of Vector's AI system.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AssumeBehaviorControl(self, request, context):
    """Acquire control of Vector's AI system.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AppIntent(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CancelFaceEnrollment(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RequestEnrolledNames(self, request, context):
    """Get a list of names and their IDs.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateEnrolledFaceByID(self, request, context):
    """Update the name enrolled for a given face.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def EraseEnrolledFaceByID(self, request, context):
    """Erase the enrollment (name) record for the face with this ID.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def EraseAllEnrolledFaces(self, request, context):
    """Erase the enrollment (name) records for all faces.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetFaceToEnroll(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def EnableVisionMode(self, request, context):
    """Turns on the provided vision mode.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GoToPose(self, request, context):
    """Tells Vector to drive to the specified pose and orientation.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DockWithCube(self, request, context):
    """Tells Vector to dock with a light cube with a given approach angle and distance.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DriveOffCharger(self, request, context):
    """Drive Vector off the charger.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DriveOnCharger(self, request, context):
    """Drive Vector onto the charger.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetOnboardingState(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SendOnboardingInput(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PhotosInfo(self, request, context):
    """Get the photos info.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Photo(self, request, context):
    """Get a photo by ID.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Thumbnail(self, request, context):
    """Get a thumbnail by ID.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeletePhoto(self, request, context):
    """Delete a photo by ID.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetLatestAttentionTransfer(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PullJdocs(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateSettings(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateAccountSettings(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateUserEntitlements(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DriveStraight(self, request, context):
    """Tells Vector to drive in a straight line.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def TurnInPlace(self, request, context):
    """Turn the robot around its current position.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetHeadAngle(self, request, context):
    """Tell Vector's head to move to a given angle.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetLiftHeight(self, request, context):
    """Tell Vector's lift to move to a given height.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UserAuthentication(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def BatteryState(self, request, context):
    """Check the current state of the battery.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def VersionState(self, request, context):
    """Get the versioning information for Vector.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def NetworkState(self, request, context):
    """Get the network information for Vector.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SayText(self, request, context):
    """Make Vector speak text.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ConnectCube(self, request, context):
    """Attempt to connect to a cube. If a cube is currently connected,
    this will do nothing.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DisconnectCube(self, request, context):
    """Requests a disconnection from the currently connected cube.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CubesAvailable(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FlashCubeLights(self, request, context):
    """Signal a connected cube to flash its lights using the default cube
    flash animation.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ForgetPreferredCube(self, request, context):
    """Forget the robot's preferred cube. This will cause the robot to
    connect to the cube with the highest RSSI (signal strength) next
    time a connection is requested. Saves this preference to disk.
    The next cube that the robot connects to will become its
    preferred cube.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetPreferredCube(self, request, context):
    """Set the robot's preferred cube and save it to disk. The robot
    will always attempt to connect to this cube if it is available.
    This is only used in simulation for now.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetCubeLights(self, request, context):
    """Set each of the lights on the currently connected cube based on two
    rgb values each and timing data for how to transition between them.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AudioFeed(self, request, context):
    """Request an audio feed from the robot.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CameraFeed(self, request, context):
    """Request a camera feed from the robot.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CheckUpdateStatus(self, request, context):
    """CheckUpdateStatus tells if the robot is ready to reboot and update.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateAndRestart(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UploadDebugLogs(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CheckCloudConnection(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ExternalInterfaceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ProtocolVersion': grpc.unary_unary_rpc_method_handler(
          servicer.ProtocolVersion,
          request_deserializer=anki__vector_dot_messaging_dot_shared__pb2.ProtocolVersionRequest.FromString,
          response_serializer=anki__vector_dot_messaging_dot_shared__pb2.ProtocolVersionResponse.SerializeToString,
      ),
      'DriveWheels': grpc.unary_unary_rpc_method_handler(
          servicer.DriveWheels,
          request_deserializer=anki__vector_dot_messaging_dot_messages__pb2.DriveWheelsRequest.FromString,
          response_serializer=anki__vector_dot_messaging_dot_messages__pb2.DriveWheelsResponse.SerializeToString,
      ),
      'PlayAnimation': grpc.unary_unary_rpc_method_handler(
          servicer.PlayAnimation,
          request_deserializer=anki__vector_dot_messaging_dot_messages__pb2.PlayAnimationRequest.FromString,
          response_serializer=anki__vector_dot_messaging_dot_messages__pb2.PlayAnimationResponse.SerializeToString,
      ),
      'ListAnimations': grpc.unary_unary_rpc_method_handler(
          servicer.ListAnimations,
          request_deserializer=anki__vector_dot_messaging_dot_messages__pb2.ListAnimationsRequest.FromString,
          response_serializer=anki__vector_dot_messaging_dot_messages__pb2.ListAnimationsResponse.SerializeToString,
      ),
      'MoveHead': grpc.unary_unary_rpc_method_handler(
          servicer.MoveHead,
          request_deserializer=anki__vector_dot_messaging_dot_messages__pb2.MoveHeadRequest.FromString,
          response_serializer=anki__vector_dot_messaging_dot_messages__pb2.MoveHeadResponse.SerializeToString,
      ),
      'MoveLift': grpc.unary_unary_rpc_method_handler(
          servicer.MoveLift,
          request_deserializer=anki__vector_dot_messaging_dot_messages__pb2.MoveLiftRequest.FromString,
          response_serializer=anki__vector_dot_messaging_dot_messages__pb2.MoveLiftResponse.SerializeToString,
      ),
      'DisplayFaceImageRGB': grpc.unary_unary_rpc_method_handler(
          servicer.DisplayFaceImageRGB,
          request_deserializer=anki__vector_dot_messaging_dot_messages__pb2.DisplayFaceImageRGBRequest.FromString,
          response_serializer=anki__vector_dot_messaging_dot_messages__pb2.DisplayFaceImageRGBResponse.SerializeToString,
      ),
      'EventStream': grpc.unary_stream_rpc_method_handler(
          servicer.EventStream,
          request_deserializer=anki__vector_dot_messaging_dot_shared__pb2.EventRequest.FromString,
          response_serializer=anki__vector_dot_messaging_dot_shared__pb2.EventResponse.SerializeToString,
      ),
      'BehaviorControl': grpc.stream_stream_rpc_method_handler(
          servicer.BehaviorControl,
          request_deserializer=anki__vector_dot_messaging_dot_behavior__pb2.BehaviorControlRequest.FromString,
          response_serializer=anki__vector_dot_messaging_dot_behavior__pb2.BehaviorControlResponse.SerializeToString,
      ),
      'AssumeBehaviorControl': grpc.unary_stream_rpc_method_handler(
          servicer.AssumeBehaviorControl,
          request_deserializer=anki__vector_dot_messaging_dot_behavior__pb2.BehaviorControlRequest.FromString,
          response_serializer=anki__vector_dot_messaging_dot_behavior__pb2.BehaviorControlResponse.SerializeToString,
      ),
      'AppIntent': grpc.unary_unary_rpc_method_handler(
          servicer.AppIntent,
          request_deserializer=anki__vector_dot_messaging_dot_messages__pb2.AppIntentRequest.FromString,
          response_serializer=anki__vector_dot_messaging_dot_messages__pb2.AppIntentResponse.SerializeToString,
      ),
      'CancelFaceEnrollment': grpc.unary_unary_rpc_method_handler(
          servicer.CancelFaceEnrollment,
          request_deserializer=anki__vector_dot_messaging_dot_messages__pb2.CancelFaceEnrollmentRequest.FromString,
          response_serializer=anki__vector_dot_messaging_dot_messages__pb2.CancelFaceEnrollmentResponse.SerializeToString,
      ),
      'RequestEnrolledNames': grpc.unary_unary_rpc_method_handler(
          servicer.RequestEnrolledNames,
          request_deserializer=anki__vector_dot_messaging_dot_messages__pb2.RequestEnrolledNamesRequest.FromString,
          response_serializer=anki__vector_dot_messaging_dot_messages__pb2.RequestEnrolledNamesResponse.SerializeToString,
      ),
      'UpdateEnrolledFaceByID': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateEnrolledFaceByID,
          request_deserializer=anki__vector_dot_messaging_dot_messages__pb2.UpdateEnrolledFaceByIDRequest.FromString,
          response_serializer=anki__vector_dot_messaging_dot_messages__pb2.UpdateEnrolledFaceByIDResponse.SerializeToString,
      ),
      'EraseEnrolledFaceByID': grpc.unary_unary_rpc_method_handler(
          servicer.EraseEnrolledFaceByID,
          request_deserializer=anki__vector_dot_messaging_dot_messages__pb2.EraseEnrolledFaceByIDRequest.FromString,
          response_serializer=anki__vector_dot_messaging_dot_messages__pb2.EraseEnrolledFaceByIDResponse.SerializeToString,
      ),
      'EraseAllEnrolledFaces': grpc.unary_unary_rpc_method_handler(
          servicer.EraseAllEnrolledFaces,
          request_deserializer=anki__vector_dot_messaging_dot_messages__pb2.EraseAllEnrolledFacesRequest.FromString,
          response_serializer=anki__vector_dot_messaging_dot_messages__pb2.EraseAllEnrolledFacesResponse.SerializeToString,
      ),
      'SetFaceToEnroll': grpc.unary_unary_rpc_method_handler(
          servicer.SetFaceToEnroll,
          request_deserializer=anki__vector_dot_messaging_dot_messages__pb2.SetFaceToEnrollRequest.FromString,
          response_serializer=anki__vector_dot_messaging_dot_messages__pb2.SetFaceToEnrollResponse.SerializeToString,
      ),
      'EnableVisionMode': grpc.unary_unary_rpc_method_handler(
          servicer.EnableVisionMode,
          request_deserializer=anki__vector_dot_messaging_dot_messages__pb2.EnableVisionModeRequest.FromString,
          response_serializer=anki__vector_dot_messaging_dot_messages__pb2.EnableVisionModeResponse.SerializeToString,
      ),
      'GoToPose': grpc.unary_unary_rpc_method_handler(
          servicer.GoToPose,
          request_deserializer=anki__vector_dot_messaging_dot_messages__pb2.GoToPoseRequest.FromString,
          response_serializer=anki__vector_dot_messaging_dot_messages__pb2.GoToPoseResponse.SerializeToString,
      ),
      'DockWithCube': grpc.unary_unary_rpc_method_handler(
          servicer.DockWithCube,
          request_deserializer=anki__vector_dot_messaging_dot_messages__pb2.DockWithCubeRequest.FromString,
          response_serializer=anki__vector_dot_messaging_dot_messages__pb2.DockWithCubeResponse.SerializeToString,
      ),
      'DriveOffCharger': grpc.unary_unary_rpc_method_handler(
          servicer.DriveOffCharger,
          request_deserializer=anki__vector_dot_messaging_dot_messages__pb2.DriveOffChargerRequest.FromString,
          response_serializer=anki__vector_dot_messaging_dot_messages__pb2.DriveOffChargerResponse.SerializeToString,
      ),
      'DriveOnCharger': grpc.unary_unary_rpc_method_handler(
          servicer.DriveOnCharger,
          request_deserializer=anki__vector_dot_messaging_dot_messages__pb2.DriveOnChargerRequest.FromString,
          response_serializer=anki__vector_dot_messaging_dot_messages__pb2.DriveOnChargerResponse.SerializeToString,
      ),
      'GetOnboardingState': grpc.unary_unary_rpc_method_handler(
          servicer.GetOnboardingState,
          request_deserializer=anki__vector_dot_messaging_dot_messages__pb2.OnboardingStateRequest.FromString,
          response_serializer=anki__vector_dot_messaging_dot_messages__pb2.OnboardingStateResponse.SerializeToString,
      ),
      'SendOnboardingInput': grpc.unary_unary_rpc_method_handler(
          servicer.SendOnboardingInput,
          request_deserializer=anki__vector_dot_messaging_dot_messages__pb2.OnboardingInputRequest.FromString,
          response_serializer=anki__vector_dot_messaging_dot_messages__pb2.OnboardingInputResponse.SerializeToString,
      ),
      'PhotosInfo': grpc.unary_unary_rpc_method_handler(
          servicer.PhotosInfo,
          request_deserializer=anki__vector_dot_messaging_dot_messages__pb2.PhotosInfoRequest.FromString,
          response_serializer=anki__vector_dot_messaging_dot_messages__pb2.PhotosInfoResponse.SerializeToString,
      ),
      'Photo': grpc.unary_unary_rpc_method_handler(
          servicer.Photo,
          request_deserializer=anki__vector_dot_messaging_dot_messages__pb2.PhotoRequest.FromString,
          response_serializer=anki__vector_dot_messaging_dot_messages__pb2.PhotoResponse.SerializeToString,
      ),
      'Thumbnail': grpc.unary_unary_rpc_method_handler(
          servicer.Thumbnail,
          request_deserializer=anki__vector_dot_messaging_dot_messages__pb2.ThumbnailRequest.FromString,
          response_serializer=anki__vector_dot_messaging_dot_messages__pb2.ThumbnailResponse.SerializeToString,
      ),
      'DeletePhoto': grpc.unary_unary_rpc_method_handler(
          servicer.DeletePhoto,
          request_deserializer=anki__vector_dot_messaging_dot_messages__pb2.DeletePhotoRequest.FromString,
          response_serializer=anki__vector_dot_messaging_dot_messages__pb2.DeletePhotoResponse.SerializeToString,
      ),
      'GetLatestAttentionTransfer': grpc.unary_unary_rpc_method_handler(
          servicer.GetLatestAttentionTransfer,
          request_deserializer=anki__vector_dot_messaging_dot_messages__pb2.LatestAttentionTransferRequest.FromString,
          response_serializer=anki__vector_dot_messaging_dot_messages__pb2.LatestAttentionTransferResponse.SerializeToString,
      ),
      'PullJdocs': grpc.unary_unary_rpc_method_handler(
          servicer.PullJdocs,
          request_deserializer=anki__vector_dot_messaging_dot_settings__pb2.PullJdocsRequest.FromString,
          response_serializer=anki__vector_dot_messaging_dot_settings__pb2.PullJdocsResponse.SerializeToString,
      ),
      'UpdateSettings': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateSettings,
          request_deserializer=anki__vector_dot_messaging_dot_settings__pb2.UpdateSettingsRequest.FromString,
          response_serializer=anki__vector_dot_messaging_dot_settings__pb2.UpdateSettingsResponse.SerializeToString,
      ),
      'UpdateAccountSettings': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateAccountSettings,
          request_deserializer=anki__vector_dot_messaging_dot_settings__pb2.UpdateAccountSettingsRequest.FromString,
          response_serializer=anki__vector_dot_messaging_dot_settings__pb2.UpdateAccountSettingsResponse.SerializeToString,
      ),
      'UpdateUserEntitlements': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateUserEntitlements,
          request_deserializer=anki__vector_dot_messaging_dot_settings__pb2.UpdateUserEntitlementsRequest.FromString,
          response_serializer=anki__vector_dot_messaging_dot_settings__pb2.UpdateUserEntitlementsResponse.SerializeToString,
      ),
      'DriveStraight': grpc.unary_unary_rpc_method_handler(
          servicer.DriveStraight,
          request_deserializer=anki__vector_dot_messaging_dot_messages__pb2.DriveStraightRequest.FromString,
          response_serializer=anki__vector_dot_messaging_dot_messages__pb2.DriveStraightResponse.SerializeToString,
      ),
      'TurnInPlace': grpc.unary_unary_rpc_method_handler(
          servicer.TurnInPlace,
          request_deserializer=anki__vector_dot_messaging_dot_messages__pb2.TurnInPlaceRequest.FromString,
          response_serializer=anki__vector_dot_messaging_dot_messages__pb2.TurnInPlaceResponse.SerializeToString,
      ),
      'SetHeadAngle': grpc.unary_unary_rpc_method_handler(
          servicer.SetHeadAngle,
          request_deserializer=anki__vector_dot_messaging_dot_messages__pb2.SetHeadAngleRequest.FromString,
          response_serializer=anki__vector_dot_messaging_dot_messages__pb2.SetHeadAngleResponse.SerializeToString,
      ),
      'SetLiftHeight': grpc.unary_unary_rpc_method_handler(
          servicer.SetLiftHeight,
          request_deserializer=anki__vector_dot_messaging_dot_messages__pb2.SetLiftHeightRequest.FromString,
          response_serializer=anki__vector_dot_messaging_dot_messages__pb2.SetLiftHeightResponse.SerializeToString,
      ),
      'UserAuthentication': grpc.unary_unary_rpc_method_handler(
          servicer.UserAuthentication,
          request_deserializer=anki__vector_dot_messaging_dot_shared__pb2.UserAuthenticationRequest.FromString,
          response_serializer=anki__vector_dot_messaging_dot_shared__pb2.UserAuthenticationResponse.SerializeToString,
      ),
      'BatteryState': grpc.unary_unary_rpc_method_handler(
          servicer.BatteryState,
          request_deserializer=anki__vector_dot_messaging_dot_messages__pb2.BatteryStateRequest.FromString,
          response_serializer=anki__vector_dot_messaging_dot_messages__pb2.BatteryStateResponse.SerializeToString,
      ),
      'VersionState': grpc.unary_unary_rpc_method_handler(
          servicer.VersionState,
          request_deserializer=anki__vector_dot_messaging_dot_messages__pb2.VersionStateRequest.FromString,
          response_serializer=anki__vector_dot_messaging_dot_messages__pb2.VersionStateResponse.SerializeToString,
      ),
      'NetworkState': grpc.unary_unary_rpc_method_handler(
          servicer.NetworkState,
          request_deserializer=anki__vector_dot_messaging_dot_messages__pb2.NetworkStateRequest.FromString,
          response_serializer=anki__vector_dot_messaging_dot_messages__pb2.NetworkStateResponse.SerializeToString,
      ),
      'SayText': grpc.unary_unary_rpc_method_handler(
          servicer.SayText,
          request_deserializer=anki__vector_dot_messaging_dot_messages__pb2.SayTextRequest.FromString,
          response_serializer=anki__vector_dot_messaging_dot_messages__pb2.SayTextResponse.SerializeToString,
      ),
      'ConnectCube': grpc.unary_unary_rpc_method_handler(
          servicer.ConnectCube,
          request_deserializer=anki__vector_dot_messaging_dot_cube__pb2.ConnectCubeRequest.FromString,
          response_serializer=anki__vector_dot_messaging_dot_cube__pb2.ConnectCubeResponse.SerializeToString,
      ),
      'DisconnectCube': grpc.unary_unary_rpc_method_handler(
          servicer.DisconnectCube,
          request_deserializer=anki__vector_dot_messaging_dot_cube__pb2.DisconnectCubeRequest.FromString,
          response_serializer=anki__vector_dot_messaging_dot_cube__pb2.DisconnectCubeResponse.SerializeToString,
      ),
      'CubesAvailable': grpc.unary_unary_rpc_method_handler(
          servicer.CubesAvailable,
          request_deserializer=anki__vector_dot_messaging_dot_cube__pb2.CubesAvailableRequest.FromString,
          response_serializer=anki__vector_dot_messaging_dot_cube__pb2.CubesAvailableResponse.SerializeToString,
      ),
      'FlashCubeLights': grpc.unary_unary_rpc_method_handler(
          servicer.FlashCubeLights,
          request_deserializer=anki__vector_dot_messaging_dot_cube__pb2.FlashCubeLightsRequest.FromString,
          response_serializer=anki__vector_dot_messaging_dot_cube__pb2.FlashCubeLightsResponse.SerializeToString,
      ),
      'ForgetPreferredCube': grpc.unary_unary_rpc_method_handler(
          servicer.ForgetPreferredCube,
          request_deserializer=anki__vector_dot_messaging_dot_cube__pb2.ForgetPreferredCubeRequest.FromString,
          response_serializer=anki__vector_dot_messaging_dot_cube__pb2.ForgetPreferredCubeResponse.SerializeToString,
      ),
      'SetPreferredCube': grpc.unary_unary_rpc_method_handler(
          servicer.SetPreferredCube,
          request_deserializer=anki__vector_dot_messaging_dot_cube__pb2.SetPreferredCubeRequest.FromString,
          response_serializer=anki__vector_dot_messaging_dot_cube__pb2.SetPreferredCubeResponse.SerializeToString,
      ),
      'SetCubeLights': grpc.unary_unary_rpc_method_handler(
          servicer.SetCubeLights,
          request_deserializer=anki__vector_dot_messaging_dot_cube__pb2.SetCubeLightsRequest.FromString,
          response_serializer=anki__vector_dot_messaging_dot_cube__pb2.SetCubeLightsResponse.SerializeToString,
      ),
      'AudioFeed': grpc.unary_stream_rpc_method_handler(
          servicer.AudioFeed,
          request_deserializer=anki__vector_dot_messaging_dot_messages__pb2.AudioFeedRequest.FromString,
          response_serializer=anki__vector_dot_messaging_dot_messages__pb2.AudioFeedResponse.SerializeToString,
      ),
      'CameraFeed': grpc.unary_stream_rpc_method_handler(
          servicer.CameraFeed,
          request_deserializer=anki__vector_dot_messaging_dot_messages__pb2.CameraFeedRequest.FromString,
          response_serializer=anki__vector_dot_messaging_dot_messages__pb2.CameraFeedResponse.SerializeToString,
      ),
      'CheckUpdateStatus': grpc.unary_unary_rpc_method_handler(
          servicer.CheckUpdateStatus,
          request_deserializer=anki__vector_dot_messaging_dot_messages__pb2.CheckUpdateStatusRequest.FromString,
          response_serializer=anki__vector_dot_messaging_dot_messages__pb2.CheckUpdateStatusResponse.SerializeToString,
      ),
      'UpdateAndRestart': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateAndRestart,
          request_deserializer=anki__vector_dot_messaging_dot_messages__pb2.UpdateAndRestartRequest.FromString,
          response_serializer=anki__vector_dot_messaging_dot_messages__pb2.UpdateAndRestartResponse.SerializeToString,
      ),
      'UploadDebugLogs': grpc.unary_unary_rpc_method_handler(
          servicer.UploadDebugLogs,
          request_deserializer=anki__vector_dot_messaging_dot_messages__pb2.UploadDebugLogsRequest.FromString,
          response_serializer=anki__vector_dot_messaging_dot_messages__pb2.UploadDebugLogsResponse.SerializeToString,
      ),
      'CheckCloudConnection': grpc.unary_unary_rpc_method_handler(
          servicer.CheckCloudConnection,
          request_deserializer=anki__vector_dot_messaging_dot_messages__pb2.CheckCloudRequest.FromString,
          response_serializer=anki__vector_dot_messaging_dot_messages__pb2.CheckCloudResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Anki.Vector.external_interface.ExternalInterface', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
